const mongoose = require('mongoose');

const enrollmentSchema = new mongoose.Schema({
    student: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    course: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Course',
        required: true
    },
    enrolledAt: {
        type: Date,
        default: Date.now
    },
    progress: {
        type: Number,
        default: 0 // Percentage 0-100
    },
    completedLessons: [{
        type: mongoose.Schema.Types.ObjectId,
        // Assuming lessons might have IDs, or we store lesson indices/IDs relative to the course
        // For simple subdoc lessons, we might need a better strategy, but for now specific lesson tracking might be complex.
        // Storing lesson IDs if they are generated by Mongoose subdocs.
    }]
}, { timestamps: true });

// Prevent duplicate enrollments
enrollmentSchema.index({ student: 1, course: 1 }, { unique: true });

module.exports = mongoose.model('Enrollment', enrollmentSchema);